# Name: Rohan Varma
# ID: 111111111
# email: rvarm1@ucla.edu
default:
	 gcc -g lab1a.c -o lab1a
clean:
	rm -rf lab1a *.tar.gz *.o

dist: default
	tar -czf lab1a-111111111.tar.gz lab1a.c Makefile README
